/// Flutter icons OradoIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OradoIcon
///      fonts:
///       - asset: fonts/OradoIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class OradoIcon {
  OradoIcon._();

  static const _kFontFam = 'OradoIcon';
  static const String? _kFontPkg = null;

  static const IconData orders = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outlined = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
