// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtgvtkBj1aruNIL5KJJGIyO911hsZY5Qk',
    appId: '1:908590403140:web:860a272a880d59c3c0f611',
    messagingSenderId: '908590403140',
    projectId: 'oradosaleapp',
    authDomain: 'oradosaleapp.firebaseapp.com',
    storageBucket: 'oradosaleapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpipNuaOOA84P5498UL8BlpKxzbkjhFGw',
    appId: '1:364977169238:android:76de808764c3af6820acf7',
    messagingSenderId: '364977169238',
    projectId: 'orado-1eb0c',
    storageBucket: 'orado-1eb0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKLtRPh1W1XdeJSvEDHqf-9QKLZL5ComI',
    appId: '1:364977169238:ios:b94508d7bfb83c8820acf7',
    messagingSenderId: '364977169238',
    projectId: 'orado-1eb0c',
    storageBucket: 'orado-1eb0c.firebasestorage.app',
    iosBundleId: 'com.example.oradosales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFNp3d_rIMgJku6WNQlPO2d3FW7U3zGzw',
    appId: '1:908590403140:ios:6da3225d5054026dc0f611',
    messagingSenderId: '908590403140',
    projectId: 'oradosaleapp',
    storageBucket: 'oradosaleapp.firebasestorage.app',
    iosBundleId: 'com.exr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtgvtkBj1aruNIL5KJJGIyO911hsZY5Qk',
    appId: '1:908590403140:web:26671cae741992a1c0f611',
    messagingSenderId: '908590403140',
    projectId: 'oradosaleapp',
    authDomain: 'oradosaleapp.firebaseapp.com',
    storageBucket: 'oradosaleapp.firebasestorage.app',
  );
}